services:
  frontend:
    ports:
      - "3000:3000"
    build:
      context: ./frontend
      dockerfile: dockerfile.dev
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    networks:
      - dev-network

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - dev-network
    depends_on:
      - db

  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "13306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  db-data:
